"""create usluga table

Revision ID: aa85fd0e271f
Revises: 
Create Date: 2026-05-09 20:35:04.130117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa85fd0e271f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usluga',
    sa.Column('IdUsluge', sa.Integer(), nullable=False),
    sa.Column('NazivUsluge', sa.String(length=100), nullable=False),
    sa.Column('Opis', sa.Text(), nullable=True),
    sa.Column('Trajanje', sa.Integer(), nullable=False),
    sa.Column('Cijena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('IdUsluge')
    )
    op.create_index(op.f('ix_usluga_IdUsluge'), 'usluga', ['IdUsluge'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usluga_IdUsluge'), table_name='usluga')
    op.drop_table('usluga')
    # ### end Alembic commands ###
